# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('codigo', models.PositiveSmallIntegerField(verbose_name='Codigo de \xe1rea')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pre\xe7o por minuto')),
            ],
        ),
    ]
