# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone')),
                ('data', models.DateField(verbose_name='Data de nascimento')),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operadoras.Operadora')),
            ],
        ),
    ]
