# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='serial',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operadoras.Operadora'),
        ),
    ]
